---
- name: Add Microsoft VS Code repository
  community.general.zypper_repository:
    name: vscode
    repo: "{{ desktop_apps_vscode_repo_url }}"
    auto_import_keys: true
    autorefresh: true
    enabled: true
  become: true

- name: Install Flatpak
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
  become: true

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ desktop_apps_flatpaks }}"
    state: present
  become: true
