---
desktop_apps_packages:
  - MozillaFirefox
  - MozillaThunderbird
  - keepassxc
  - code
  - podman

desktop_apps_vscode_repo_url: https://packages.microsoft.com/yumrepos/vscode
desktop_apps_vscode_repo_key: https://packages.microsoft.com/keys/microsoft.asc

desktop_apps_flatpaks:
  - com.slack.Slack
  - com.valvesoftware.Steam
  - com.discordapp.Discord
  - com.dropbox.Client
