---
desktop_apps_packages:
  - MozillaFirefox
  - MozillaThunderbird
  - keepassxc
  - code
  - steam
  - discord
  - dropbox
  - podman

desktop_apps_vscode_repo_url: https://packages.microsoft.com/yumrepos/vscode
desktop_apps_vscode_repo_key: https://packages.microsoft.com/keys/microsoft.asc

desktop_apps_slack_rpm_url: https://downloads.slack-edge.com/desktop-releases/linux/x64/latest/slack-desktop-latest.x86_64.rpm
