---
- name: Load distro-specific package names
  ansible.builtin.include_vars: "{{ dotfiles_distro }}.yml"

- name: Install C/C++ development packages
  ansible.builtin.package:
    name: "{{ cpp_dev_packages }}"
    state: present
  become: true
