---
hyprland_packages:
  - hyprland
  - uwsm
  - xdg-desktop-portal-hyprland
  - waybar
  - wofi
  - swaybg
  - swaylock
  - swayidle
  - mako
  - grim
  - slurp
  - wl-clipboard
  - polkit-gnome
  - greetd
  - gtkgreet
