---
dotfiles_dir: "{{ lookup('env', 'HOME') }}/.dotfiles"
dotfiles_user: "{{ lookup('env', 'USER') }}"
dotfiles_home: "{{ lookup('env', 'HOME') }}"

distro_key_map:
  Ubuntu: ubuntu
  openSUSE Tumbleweed: tumbleweed
  OracleLinux: oracle
