---
name: Test Installation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-24.04
            image: ubuntu:24.04
            install_prereqs: apt-get update && apt-get install -y git sudo hostname
            install_cmd: ./install.sh --env wsl
          - name: tumbleweed
            image: opensuse/tumbleweed
            install_prereqs: zypper --non-interactive dup && zypper install -y git sudo hostname
            install_cmd: ./install.sh --env desktop
          - name: oracle-9
            image: oraclelinux:9
            install_prereqs: dnf install -y git sudo hostname
            install_cmd: ./install.sh --env wsl

    name: ${{ matrix.name }}
    container:
      image: ${{ matrix.image }}

    steps:
      - name: Install prerequisites
        run: ${{ matrix.install_prereqs }}

      - name: Mark workspace as safe for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Symlink to expected path
        run: ln -sf "$GITHUB_WORKSPACE" "$HOME/.dotfiles"

      - name: Run install
        run: ${{ matrix.install_cmd }}
        env:
          USER: root
